node1:
  role: receiver_ai_orchestrator
  ip: 192.168.29.20
  udp_port: 5000
  api_port: 8080
  metrics_port: 9101
node2:
  role: camera_streamer
  ip: 192.168.29.188
  api_port: 8082
  camera_device: /dev/video0
  default_mode: mjpeg_720p30
  supported_modes:
  - mjpeg_480p30
  - mjpeg_720p30
  - mjpeg_720p60
network:
  transport: UDP/RTP
  rtp_caps: application/x-rtp,media=video,clock-rate=90000,encoding-name=JPEG,payload=26
  low_latency: true
